Repository AxonIQ/axon-server-api, pull requests merged in 2019-11, with the labels that each got.

#14 Unknown request
  src/main/proto/command.proto
  src/main/proto/common.proto
  src/main/proto/control.proto
  src/main/proto/query.proto
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#17 Instruction acknowlegdement
  src/main/proto/command.proto
  src/main/proto/common.proto
  src/main/proto/control.proto
  src/main/proto/query.proto
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#18 Support loadFactor in AxonServer for Commands
  src/main/proto/command.proto
Labels: Priority 2: Should
