Repository AxonIQ/axon-server-api, pull requests merged in 2020-03, with the labels that each got.

#20 Added possibility to use local event store when querying for events.
  src/main/proto/event.proto
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#19 Introduces a InstructionResult that represents the result of the execution of an instruction
  src/main/proto/common.proto
  src/main/proto/control.proto
Labels: Status: In Progress, Type: Feature

#21 Adjusted JavaDoc for ListEvents.
  src/main/proto/event.proto
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement
